### ISSUE TITLE
syncing time entries failed

### ISSUE THREAD

**Issue by funkydonkey** [reify-academy/fibery-toggl-integration#5] opened 2023-05-30 14:53 UTC
Hi, Maxim! In advance, I want to say many thanks for so vital integration! But I've faced troubles at the Time entries syncing step. Workspaces, Clients, and Projects sync brilliantly (if I switched off Time entries sync), but on Time entries step sync always crashes. I tried to reestablish integration a couple of times, but it hasn't led me to success. 
Could you kindly answer me what should I do?

**Comment by Maxim-Filimonov** [comment] 2023-05-31 06:00
Hi @funkydonkey, Thanks for reporting the issue!
It was caused by changes to Toggl API we didn't anticipate. 
It's already fixed with the latest [change](https://github.com/reify-academy/fibery-toggl-integration/commit/503e9fb5e1a3ee164ca71c9e805089831b9a0498)
Please, confirm if it works for you now.

**Comment by funkydonkey** [comment] 2023-05-31 07:28
Yeah, now it's work! Thank you so much for so quick response! 
Wish you good luck with your further projects!

**Closed as completed** 2023-05-31 09:06 UTC
